const { test, expect } = require('@playwright/test');
const { LuluSearchPage } = require ('../pages/lulu-search.js')

/*test('has title in other file', async ({ page }) => {
    await page.goto('https://www.lulu.com/search?page=1&q=new&pageSize=10&adult_audience_rating=00');
  
    // Expect a title "to contain" a substring.
    await expect(page).toHaveTitle(/Shop/);
  });*/

/*test('check page object have title', async ({ page }) => {
    const luluSearch = new LuluSearchPage(page);
    await luluSearch.goto();
    await expect(page).toHaveTitle(/Shop/);

})*/

test('BKS-03001 Search for any product', async ({ page }) => {
    
    const luluSearch = new LuluSearchPage(page);
    await luluSearch.goto();
    await luluSearch.enterValueToSearchInputField('');
    await luluSearch.searchResultIsNotNull();

    //1. click on search field
    //2. leave empty and click <enter>
    //3. check if result is not null
})

/*test('BLS-03002 Search for product in non default language', async ({ page }) => {
    //1. change language to random non-default one, assume default is English
    //2. click on search field
    //3.  leave empty and click <enter>
    //4. check if result is null
})*/

/*test('BKS-03003 Search for non existing product', async ({ page }) => {
  //1. click on seacrh field
  //2. enter 'nienapisana' <-- or random string
  //3. click <enter>
  //4. check number of products
  //5. check if 'No search results' information exists
  const luluSearch = new LuluSearchPage(page);
  await luluSearch.goto();
  await luluSearch.enterValueToSearchInputField('abacasda');
  await luluSearch.searchResultIsNull();
  await luluSearch.noResultMessage();
  expect(noResultMessage).toBeVisible;

})*/

/*test('autogenerated lulu test', async ({ page }) => {
  await page.goto('https://www.lulu.com/search?page=1&pageSize=10&adult_audience_rating=00');
  await page.getByTestId('header-search-input').click();
  await page.getByTestId('header-search-input').press('Enter');
  expect(page.locator('.ProductItem_productItem__cover__0p_rT')).toBeVisible();
});*/

/*test('test autogenerated', async ({ page }) => {
    
  await page.goto('https://www.lulu.com/search?page=1&pageSize=10&adult_audience_rating=00');
  await page.getByTestId('header-search-input').click();
  await page.getByTestId('header-search-input').press('Enter');
  var count = await page.getByTestId('produdct-title').count();
  expect(count).toBeGreaterThanOrEqual(1);
  //const count = await page.getByRole('listitem').count();
});*/

/*test('test autogenerated 2', async ({ page }) => {
    await page.goto('https://www.lulu.com/search?page=1&pageSize=10&adult_audience_rating=00');
    await page.getByTestId('header-search-input').fill('nienapisana');
    await page.getByTestId('header-search-input').press('Enter');
    const count = await page.getByTestId('produdct-title').count();
    expect(count).toBeLessThan(1);
  });*/