const { test, expect } = require('@playwright/test');
const { LuluSearchPage } = require ('../pages/lulu-search.js')

/*test('has title in other file', async ({ page }) => {
    await page.goto('https://www.lulu.com/search?page=1&q=new&pageSize=10&adult_audience_rating=00');
  
    // Expect a title "to contain" a substring.
    await expect(page).toHaveTitle(/Shop/);
  });*/

test('check page object have title', async ({ page }) => {
    const luluSearch = new LuluSearchPage(page);
    await luluSearch.goto();
    await expect(page).toHaveTitle(/Shop/);

})

/*test('BKS-03001 Search for any product', async ({ page }) => {
    const luluSearch = new LuluSearchPage(page);
    await luluSearch.goto();
    await page.getByTestId('header-search-input').fill('New');
    await page.keyboard.press('Enter');
    expect(page.getByTestId('product-title')).toHaveValues();



    //1. click on seacrh field
    //2. leave empty and click <enter>
    //3. check if result is not null
})*/

/*test('BLS-03002 Search for product in non default language', async ({ page }) => {
    //1. change language to random non-default one, assume default is English
    //2. click on search field
    //3.  leave empty and click <enter>
    //4. check if result is null
})*/

/*test('autogenerated lulu test', async ({ page }) => {
  await page.goto('https://www.lulu.com/search?page=1&pageSize=10&adult_audience_rating=00');
  await page.getByTestId('header-search-input').click();
  await page.getByTestId('header-search-input').press('Enter');
  expect(page.locator('.ProductItem_productItem__cover__0p_rT')).toBeVisible();
});*/

test('test autogenerated', async ({ page }) => {
    
  await page.goto('https://www.lulu.com/search?page=1&pageSize=10&adult_audience_rating=00');
  await page.getByTestId('header-search-input').click();
  await page.getByTestId('header-search-input').press('Enter');
  const count = await page.getByTestId('produdct-title').count();
  expect(count).toBeGreaterThan(1);
  //const count = await page.getByRole('listitem').count();
});

test('test autogenerated 2', async ({ page }) => {
    await page.goto('https://www.lulu.com/search?page=1&pageSize=10&adult_audience_rating=00');
    await page.getByTestId('header-search-input').fill('nienapisana');
    await page.getByTestId('header-search-input').press('Enter');
    const count = await page.getByTestId('produdct-title').count();
    expect(count).toBeLessThan(1);
  });